#%Dialect 1.0

dialect: Dynamic
version: 0.1

documents:
  root:
    encodes: RootNode

nodeMappings:
  RootNode:
    mapping:
      superExample:
        range: string
      superExampleAdditional:
        range: string