#%RAML 1.0 Vocabulary

vocabulary: Anypoint Vocabulary

usage: The common vocabulary to define Anypoint concepts

base: http://mulesoft.com/vocabularies/anypoint#

classTerms:

  Configuration:
    displayName: Configuration
    description: Deployment configuration
    properties:
      - assets

  Asset:
      displayName: Asset
      description: Reference to an asset that is store in exchange

  VDPAsset:
    displayName: Asset
    description: Reference to an asset that is store in exchange
    extends: Asset
    properties:
      - group
      - artifact
      - version
      - classifier
      - packaging

  CSMAsset:
    displayName: Asset
    description: Reference to an asset that is store in exchange
    extends: Asset
    properties:
      - group
      - artifact
      - version
      - classifier
      - packaging

propertyTerms:

  assets:
    displayName: Assets
    range: Asset

  asset_name:
    displayName: Asset Name
    range: string

  group:
    displayName: Group
    range: string

  artifact:
    displayName: artifact
    range: string

  version:
    displayName: version
    range: string

  classifier:
    displayName: classifier
    range: string

  packaging:
    displayName: packaging
    range: string