#%Dialect 1.0

### This is created by Exchange and POST to AMC Atlas

dialect: ClientIdEnforcement
version: 0.1

uses:
  amc: ../amc.raml

documents:
  root:
    encodes: RootNode

nodeMappings:

  RootNode:
    mapping:
      credentialsOriginHasHttpBasicAuthenticationHeader:
        range: string
      clientIdExpression:
        propertyTerm: amc.PlainSecret
        range: string
      clientSecretExpression:
        range: string
