#%Dialect 1.0

### This is created by Exchange and POST to AMC Atlas

dialect: CORS
version: 0.1

uses:
  amc: ../amc.raml

documents:
  root:
    encodes: RootNode

nodeMappings:

  RootNode:
    mapping:
      publicResource:
        range: boolean
      supportCredentials:
        range: boolean
      originGroups:
        range: string
        allowMultiple: true
