#%Dialect 1.0

dialect: Mule Application
version: 0.1

uses:
  amc: ../vocabularies/amc.yaml

external:
  mule: http://mulesoft.com/vocabularies/mule#

documents:
  root:
    encodes: ConfigurationNode

nodeMappings:
  ConfigurationNode:
    classTerm: mule.ConfigurationNode
    mapping:
      transports:
        range: TransportNode
        mandatory: true
      globalConfiguration:
        range: GlobalConfigurationNode

  TransportNode:
    classTerm: mule.TransportNode
    mapping:
      rest.agent.transport:
        range: RESTTransportNode
      websocket.transport:
        range: WSTransportNode

  RESTTransportNode:
    classTerm: mule.RESTTransportNode
    mapping:
      enabled:
        range: boolean
      port:
        range: integer

  WSTransportNode:
    classTerm: mule.WSTransportNode
    mapping:
      enabled:
        range: boolean
      consoleUri:
        range: string
      handshake:
        range: HandshakeNode

  HandshakeNode:
    classTerm: mule.HandshakeNode
    mapping:
      enabled:
        range: boolean
      body:
        range: anyNode

  GlobalConfigurationNode:
    classTerm: mule.GlobalConfigurationNode
    mapping:
      security:
        range: SecurityNode
      authenticationProxy:
        range: AuthenticationProxyNode

  SecurityNode:
    classTerm: mule.SecurityNode
    mapping:
      keyStorePassword:
        propertyTerm: amc.keyStorePassword
        range: string
      keyStoreAlias:
        range: string
      keyStoreAliasPassword:
        propertyTerm: amc.keyStorePasswordAlias
        range: string

  AuthenticationProxyNode:
    classTerm: mule.AuthenticationProxyNode
    mapping:
      endpoint:
        range: string