PREFIX apiContract: <http://a.ml/vocabularies/apiContract#>
PREFIX core: <http://a.ml/vocabularies/core#>

SELECT ?path ?ep
WHERE {
    ?ep a apiContract:EndPoint ;
        apiContract:path ?path ;
        apiContract:supportedOperation ?op .
    ?op apiContract:returns ?ret .
    ?ret apiContract:payload ?payload .
    ?payload core:mediaType "application/json" .
}
