PREFIX api: <http://a.ml/vocabularies/apiContract#>
PREFIX core: <http://a.ml/vocabularies/core#>

SELECT ?path ?ep
WHERE {
    ?ep a api:EndPoint ;
        api:path ?path ;
        api:supportedOperation / api:returns / api:payload / core:mediaType "application/json"
}
