PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX amc: <http://mulesoft.com/vocabularies/amc#>
PREFIX core: <http://a.ml/vocabularies/core#>

SELECT ?property ?name
WHERE {
    ?property rdfs:subPropertyOf amc:secret ;
              core:displayName ?name .
#    FILTER(?property != amc:secret)
}