PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX amc: <http://mulesoft.com/vocabularies/amc#>

SELECT DISTINCT ?subject ?property ?value
WHERE {
    ?subject ?property ?value .
    ?property rdfs:subPropertyOf amc:secret .
    FILTER(?property != amc:secret)
}