#%Vocabulary 1.0
usage: The common vocabulary to define AMC concepts
base: http://mulesoft.com/vocabularies/amc#

classTerms:

  DynamicContainer:
    displayName: DynamicContainer
    description: Hint to mark a dynamic container

  Asset:
    displayName: Asset
    description: Reference to an asset

  ExchangeAsset:
    displayName: Exchange Asset
    description: Reference to an Exchange asset
    extends: Asset

propertyTerms:

  Secret:
    displayName: Secret
    description: Generic Secret Reference
    range: string

  PlainSecret:
    displayName: PlainSecret
    description: Plain Secret
    extends: Secret