#%Dialect 1.0

dialect: MuleApplication
version: 0.1

uses:
  amc: amc.raml

documents:
  root:
    encodes: ConfigurationNode

nodeMappings:

  ConfigurationNode:
    mapping:
      assets:
        mapKey: name
        range:
          - ExchangeAssetNode
      mule.agent.application.properties.service:
        range: ApplicationPropertiesNode
      fragments:
        range: FragmentNode

  ExchangeAssetNode:
    classTerm: amc.ExchangeAsset
    mapping:
      name:
        range: string
      groupId:
        range: string
      artifactId:
        range: string
      version:
        range: string
      classifier:
        range: string
      packaging:
        range: string
      exchangeType:
        range: string

  ApplicationPropertiesNode:
    mapping:
      applicationName:
        range: string

  FragmentNode:
    mapping:
      api:
        range: APINode
      policies:
        allowMultiple: true
        range: PolicyNode

  APINode:
    mapping:
      apiId:
        range: number
      masterOrganizationId:
        range: string
      organizationId:
        range: string
      groupId:
        range: string
      assetId:
        range: string
      version:
        range: string
      productVersion:
        range: string
      autodiscoveryInstanceName:
        range: string
      providerId:
        range: string
      exchangeAssetName:
        range: string
      instanceLabel:
        range: string
      environmentId:
        range: string
      legacyApiIdentifier:
        range: number
      endpointType:
        range: string
      endpointUri:
        range: string
      proxyUri:
        range: string
      instanceName:
        range: string
      identityManagement:
        range: IdentityManagementNode
      lastModification:
        range: number

  IdentityManagementNode:
    mapping:
      clientId:
        propertyTerm: amc.PlainSecret
        range: string
      clientSecret:
        range: string
      tokenUrl:
        propertyTerm: amc.PlainSecret
        range: string

  PolicyNode:
    mapping:
      policyTemplateId:
        range: string
      order:
        range: number
      pointcutData:
        range: string
      policyId:
        range: number
      configuration:
        range: anyNode
      template:
        range: TemplateNode
      version:
        range: number

  TemplateNode:
    mapping:
      groupId:
        range: string
      assetId:
        range: string
      assetVersion:
        range: string