PREFIX amc: <http://mulesoft.com/vocabularies/amc#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?x ?secret ?z WHERE {
    ?secret rdfs:subPropertyOf amc:Secret .
    ?x ?secret ?z
}
LIMIT 100