#%MuleRuntime 0.1

# Declaration of global configuration elements here
globalHttpConfig:

  # Temporary syntax, there are many ways of doing this
  accounts_http_config:
    config:
      - param: Method
        value: Get
      - param: Path
        value: /get-{type}s-by-id
      - param: Ref
        value: HTTP_Request_config_Accounts
      - param: Uri
        expression: '#[{"type" : vars.sObjectType}]'
      - param: Query
        expression: '#[{"id" : vars.sObjectId}]'


# The description of the flow starts here, it can refer to the declared elements
# like the accounts_http_config global configuration

name: Test Application
